name: Build OpenWrt Passwall

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential clang flex bison gawk gettext \
            libncurses5-dev libssl-dev rsync unzip zlib1g-dev zstd \
            python3 python3-pip python3-setuptools python3-wheel python3-packaging subversion

      - name: Download OpenWrt SDK (NanoPi M4 rk3399)
        run: |
          wget https://downloads.openwrt.org/releases/24.10.1/targets/rockchip/armv8/openwrt-sdk-24.10.1-rockchip-armv8_gcc-13.3.0_musl.Linux-x86_64.tar.zst
          tar -I zstd -xvf openwrt-sdk-24.10.1-rockchip-armv8_gcc-13.3.0_musl.Linux-x86_64.tar.zst
          mv openwrt-sdk-24.10.1-rockchip-armv8_gcc-13.3.0_musl.Linux-x86_64 sdk

      - name: Update feeds
        run: |
          cd sdk
          echo "src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall-packages" >> feeds.conf.default
          echo "src-git passwall https://github.com/xiaorouji/openwrt-passwall" >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

          # 替换官方 rust 为 rust-bin
          rm -rf feeds/packages/lang/rust
          svn export https://github.com/openwrt/packages/trunk/lang/rust feeds/packages/lang/rust

      - name: Configure .config
        run: |
          cd sdk
          rm -f .config
          cat >> .config <<EOF
          CONFIG_PACKAGE_luci-app-passwall=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Xray=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_SingBox=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Hysteria=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_NaiveProxy=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_TUIC_Client=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Rust_Client=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Rust_Server=y
          EOF
          make defconfig

      - name: Build
        run: |
          cd sdk
          make package/luci-app-passwall/compile -j$(nproc) V=sc

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: passwall-ipk
          path: sdk/bin/packages/*/*/*.ipk
